---
- name: Find KB Docs
  hosts: " {{ server_ip }}"
  #become: true
  tasks:
    - name: find files
      find:
        paths: /data/ftp/files/
        patterns: "(.*{{ kb_number }}.*)$"
        use_regex: yes
        hidden: yes
      register: list_of_files
    - name: print files
      debug:
        msg: "{{ list_of_files.files }}"
