---
- name: Find KB Docs
  hosts: "{{ my_ip }}"
  #become: true
  tasks:
    - name: Check File Path for KB Name
        find:
          paths: /data/ftp/files/
          patterns: " {{ my_regex_expression }}"
          use_regex: yes
