---
- name: Find KB Docs
  hosts: all
  #become: true
  tasks:
    - name: find files
      find:
        paths: /data/ftp/files/
        patterns: "(.*kb5011644.*)$"
        use_regex: yes
        hidden: yes
      register: list_of_files
    - name: print files
      debug:
        msg: "{{ list_of_files.files }}"
