---
- name: Find KB Docs
  hosts: all
  #become: true
  tasks:
    - name: Check File Path for KB Name
      find:
        paths: /data/ftp/files/
        file_type: directory
        use_regex: yes
        patterns: '*kb5011644*'
       register: oea
